version: '3'
services:
  angular-app:
    image: frontend:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      rollback:
        parallelism: 2
        delay: 10s

  nginx:
    image: my-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - angular-app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
