name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:prod .
          docker tag  ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:prod
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:prod

      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_HOST }}
          username: ${{ secrets.SWARM_USERNAME }}
          password: ${{ secrets.SWARM_PASSWORD }}
          script: |
            docker stack deploy -c docker-compose.yml
